### ISSUE TITLE
Locating casperjs binary

### ISSUE THREAD

**Issue by neshala** [DiceHoldingsInc/casperjs-php-driver#4]
I have problems with exec in your file Driver.php, line 65.

this is not working both on my server and local mac
<pre>exec('casperjs ' . $filename . $this->optionBuilder->build(), $output);</pre>

But when i change it to this, it works
<pre>exec('/usr/local/bin/casperjs ' . $filename . $this->optionBuilder->build(), $output);</pre>

I think that this is because PHP doesn't know where to find casperjs executable file. Any idea how to solve this? Or at least to have this as optional configurable option, so it can be adjusted?

Thanks

**Comment by fguery** [comment]
For the moment you could just add that path to your $PATH at os level, but you're right it should be configurable. 
I'll try to have a look to that tomorrow

**Comment by jnardiello** [comment]
@fguery I will review your PR soon so that we can merge it to master.

**Comment by fguery** [comment]
Windows is not really supported by the PR, I have no machine to test it :/

**Comment by ArlingtonHouse** [comment]
I'm having this same problem in Linux with Symfony.   PhantomJS-php has a method $phantom->getEngine()->setPath('../bin/phantomjs'); is there anything equivalent with CasperJS-php-driver ?  Thanks!

**Comment by fguery** [comment]
I'm not sure I understand, you can pass the path to your casperjs
executable through the constructor of the Driver class.
